In [0]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd

In [0]:
train = pd.read_csv('train_no_missing_outlier.csv')
del train['id']
del train['open_date']
target='flag'
train['flag'].value_counts()
x_columns=[x for x in train.columns if x not in [target] ]
X_tot=train[x_columns]
X=X_tot.drop(columns=['caller_sum_45','caller_sum_456','record_sum_45','record_sum_456','time_sum_45','time_sum_456'])
y=train['flag']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [0]:
y_pred = clf.predict(X_test)

In [7]:
print('Accuracy for the RandomForest Tree model:',accuracy_score(y_test, y_pred))
print('Confusion matrix for the RandomForest Tree model:')
print(confusion_matrix(y_test, y_pred))

Accuracy for the RandomForest Tree model: 0.8768304565975019
Confusion matrix for the RandomForest Tree model:
[[851290  22383]
 [103010  41369]]


In [0]:
from sklearn.metrics import roc_auc_score
roc_score = roc_auc_score(y_test, y_pred)

In [9]:
roc_score

0.6304555822559829

In [10]:
clf = RandomForestClassifier(class_weight={0:0.2,1:0.8})
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight={0: 0.2, 1: 0.8},
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=None, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [11]:
y_pred = clf.predict(X_test)
print('the accuracy is:',accuracy_score(y_test, y_pred))
print('the accuracy is:',roc_auc_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

the accuracy is: 0.8773697217823844
the accuracy is: 0.621822712940904
Confusion matrix for the RandomForest model(with weight):
[[854934  18739]
 [106105  38274]]


In [12]:
clf = RandomForestClassifier(class_weight={0:0.1,1:0.9})
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('the accuracy is:',accuracy_score(y_test, y_pred))
print('the accuracy is:',roc_auc_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


the accuracy is: 0.8775042925115809
the accuracy is: 0.6186460643577336
Confusion matrix for the RandomForest model(with weight):
[[856197  17476]
 [107231  37148]]


In [13]:
clf = RandomForestClassifier(class_weight={0:0.3,1:0.7})
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('the accuracy is:',accuracy_score(y_test, y_pred))
print('the accuracy is:',roc_auc_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


the accuracy is: 0.8774325869405492
the accuracy is: 0.62494961689267
Confusion matrix for the RandomForest model(with weight):
[[853929  19744]
 [105036  39343]]


In [14]:
clf = RandomForestClassifier(class_weight={0:0.4,1:0.6})
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('the accuracy is:',accuracy_score(y_test, y_pred))
print('the accuracy is:',roc_auc_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


the accuracy is: 0.8770328038253449
the accuracy is: 0.628029561641168
Confusion matrix for the RandomForest model(with weight):
[[852376  21297]
 [103890  40489]]


In [15]:
clf = RandomForestClassifier(class_weight={0:0.5,1:0.5})
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('the accuracy is:',accuracy_score(y_test, y_pred))
print('the accuracy is:',roc_auc_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


the accuracy is: 0.8765868541096132
the accuracy is: 0.6299349564809406
Confusion matrix for the RandomForest model(with weight):
[[851173  22500]
 [103141  41238]]


In [16]:
print('Accuracy for the RandomForest Tree model(with weight):',accuracy_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

Accuracy for the RandomForest Tree model(with weight): 0.8765868541096132
Confusion matrix for the RandomForest model(with weight):
[[851173  22500]
 [103141  41238]]


In [17]:
xx=['day','record_sum_5','caller_sum_5','record_sum_6','record_sum_4','brand','time_sum_5','time_sum_4','caller_sum_4','city_flag']
X=train[xx]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = RandomForestClassifier(class_weight={0:0.2,1:0.8})
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Accuracy for the RandomForest Tree model(with weight and feature selection):',accuracy_score(y_test, y_pred))
print('Confusion matrix for the RandomForest model(with weight):')
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Accuracy for the RandomForest Tree model(with weight and feature selection): 0.8767921481417452
Confusion matrix for the RandomForest model(with weight):
[[853776  19542]
 [105890  38844]]
